services:

  backend:
    container_name: quizbattle_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      APP_ENV: local
      API_PREFIX: /api/v1
      DATABASE_URL: postgresql+asyncpg://quizbattle:quizbattle@postgres:5432/quizbattle_db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: change_me
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    container_name: quizbattle_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    container_name: quizbattle_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: quizbattle
      POSTGRES_PASSWORD: quizbattle
      POSTGRES_DB: quizbattle_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizbattle -d quizbattle_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: quizbattle_redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5