version: "3.9"

services:

  backend:
    container_name: quizbattle_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      APP_ENV: local
      API_PREFIX: /api/v1
      DATABASE_URL: postgresql+asyncpg://quizbattle:quizbattle@postgres:5432/quizbattle_db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: change_me

  frontend:
    container_name: quizbattle_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    container_name: quizbattle_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: quizbattle
      POSTGRES_PASSWORD: quizbattle
      POSTGRES_DB: quizbattle_db
    ports:
      - "5432:5432"

  redis:
    container_name: quizbattle_redis
    image: redis:7
    ports:
      - "6379:6379"