services:

  backend:
    container_name: quizbattle_backend
    image: ghcr.io/${IMAGE_OWNER_LC}/quizbattle-backend:latest
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      API_PREFIX: /api/v1
      DATABASE_URL: postgresql+asyncpg://quizbattle:${DB_PASSWORD}@postgres:5432/quizbattle_db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  frontend:
    container_name: quizbattle_frontend
    image: ghcr.io/${IMAGE_OWNER_LC}/quizbattle-frontend:latest
    ports:
      - "3000:3000"
    restart: always

  postgres:
    container_name: quizbattle_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: quizbattle
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: quizbattle_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizbattle -d quizbattle_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    container_name: quizbattle_redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
